server:
  port: 4000
  servlet:
    context-path: /id

security:
  oauth2:
    authorization:
      check-token-access: permitAll()

spring:
  security:
    user:
      password: pwd

logging:
  level:
    org.springframework.security: DEBUG
