server:
  port: 5000

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
    resource:
      token-info-uri: ${auth-server:http://localhost:4000/id}/oauth/check_token

logging:
  level:
    org.springframework.security: DEBUG
